<?php

declare(strict_types=1);

namespace Syriable\Localizer\Generator;

use Syriable\Localizer\Contracts\GenerationStrategy;
use Syriable\Localizer\Data\ExtractedString;
use Syriable\Localizer\Data\StringKind;

/**
 * Builds a nested PHP translation array from a list of ExtractedStrings.
 *
 * Each ShortKey string carries a dot-notation `key` field (e.g.
 * `"submit.label"`) which becomes the nested array path. The value
 * is generated by the supplied strategy.
 *
 * JsonKeys and strings without a `key` are silently skipped — they
 * belong in `lang/{locale}.json`, not PHP files.
 */
final class TranslationArrayBuilder
{
    /**
     * Builds a nested array from the given strings.
     *
     * @param  list<ExtractedString> $strings
     * @return array<string, mixed>
     */
    public function build(array $strings, GenerationStrategy $strategy): array
    {
        $result = [];

        foreach ($strings as $string) {
            if ($string->kind !== StringKind::ShortKey || $string->key === null || $string->key === '') {
                continue;
            }

            $value = $strategy->generate($string->value);
            $result = $this->set($result, $string->key, $value);
        }

        return $result;
    }

    /**
     * Sets a dot-notation key within a nested array, returning the updated array.
     *
     * Intermediate segments that do not yet exist are created as sub-arrays.
     * If an existing leaf value would need to become a sub-array (scalar
     * collision), the leaf is silently replaced.
     *
     * @param  array<string, mixed> $array
     * @return array<string, mixed>
     */
    private function set(array $array, string $key, string $value): array
    {
        $segments = explode('.', $key);

        if (count($segments) === 1) {
            $array[$key] = $value;

            return $array;
        }

        $first = array_shift($segments);
        $remainder = implode('.', $segments);

        /** @var array<string, mixed> $nested */
        $nested = (isset($array[$first]) && is_array($array[$first])) ? $array[$first] : [];

        $array[$first] = $this->set($nested, $remainder, $value);

        return $array;
    }
}
